### ISSUE TITLE
[BUG] artifact uploads fail when packages are deeply nest under infra

### ISSUE THREAD

**Issue by mteichtahl** [aws/aws-pdk#419]
### Describe the bug

When creating/adding packages to a code base thats based on a blue print (after cloning, committing and pushing) say for example in the structure below

```
.
├── LICENSE
├── README.md
├── approved-licenses.yaml
├── node_modules
├── nx.json
├── package.json
├── packages
│   ├── api
│   │   ├── README.md
│   │   ├── infrastructure
│   │   ├── libraries
│   │   ├── model
│   │   ├── project.json
│   │   └── runtime
│   ├── infra
│   │   └── core
│   └── website
│       ├── LICENSE
│       ├── README.md
│       ├── build
│       ├── node_modules
│       ├── package.json
│       ├── project.json
│       ├── public
│       ├── src
│       ├── tsconfig.dev.json
│       └── tsconfig.json
├── selected-options.json
├── tsconfig.dev.json
├── tsconfig.json
└── yarn.lock

15 directories, 17 files

```

The following error is generate in the upload artifact action of codecatalyst

```CLIENT_ERROR: no matching artifact paths found for artifact Diagram```

### Expected Behavior

upload artifact step in codecatalyst should completed successfully regardless of the package structure

### Current Behavior

upload artifact step fails when using deeply nest packages

### Reproduction Steps

- create a project from the CC pdk website blue print
- rehome the infra package as infra/core
- introduce a new package say infra/services/serviceOne
- commit and push

### Possible Solution

when generating pr.yaml, take into account the path of the package

for example

```
    Outputs:
      Artifacts:
        - Name: Built
          Files:
            - "**/*"
        - Name: Diagram
          Files:
            - packages/infra/core/cdk.out/cdkgraph/diagram.*
      AutoDiscoverReports:
```

### PDK version used

latest

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

N/A
